language: php

php: 7.4

fast_finish: true

jobs:
 allow_failures:
 - php: nightly

 include:
 - &lint
   env:
   - LINT

   install:
   - composer install
   - nvm install 14
   - npm install --global grunt-cli
   - npm install

   script:
   - grunt

 - &build
   addons:
    apt:
     packages:
     - fontforge

   env:
   - BUILD

   install:
   - nvm install 14
   - npm install --global grunt-cli
   - npm install

   script:
   - grunt build

 - &test-unit
   env:
   - TEST=unit

   services:
   - mysql
   - postgresql

   install:
   - composer install
   - gem install mailcatcher

   before_script:
   - echo sendmail_path=/usr/bin/env catchmail >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - mailcatcher
   - mysql -u root -e 'create database test'
   - mysqladmin -u root password test
   - psql -U postgres -c 'create database test'
   - psql -U postgres -c 'alter user postgres with password '\'test\'

   script:
   - DB_URL=mysql://root:test@127.0.0.1/test vendor/bin/phpunit
   - DB_URL=postgres://postgres:test@127.0.0.1/test vendor/bin/phpunit
   - DB_URL=sqlite://test.sqlite vendor/bin/phpunit
   -
 - <<: *test-unit
   php: 7.2

   before_install:
   - composer remove infection/infection --dev --no-update

 - <<: *test-unit
   php: 7.3

   before_install:
   - composer remove infection/infection --dev --no-update

 - <<: *test-unit
   php: nightly

   before_install:
   - composer remove sebastian/phpcpd --dev --no-update
   - composer require phpunit/phpunit 9 --dev --no-update

   install:
   - composer install --ignore-platform-reqs
   - gem install mailcatcher

 - &test-unit-windows
   os: windows

   language: sh

   env:
   - TEST=unit

   install:
   - export PATH=/c/PHP:$PATH
   - export PATH=/c/Composer:$PATH
   - choco install php --version 7.2.15 --package-parameters='/InstallDir:C:\PHP'
   - choco install composer --install-arguments='/DEV=C:\Composer /PHP=C:\PHP'
   - powershell -Command 'Invoke-WebRequest https://raw.githubusercontent.com/redaxscript/redaxscript-powershell/master/php.ini -OutFile C:\PHP\php.ini'
   - composer install

   script:
   - export DB_URL=sqlite://test.sqlite
   - vendor/bin/phpunit

 - &test-acceptance
   env:
   - TEST=acceptance

   install:
   - composer install
   - gem install mailcatcher
   - nvm install 14
   - npm install --global grunt-cli
   - npm install

   before_script:
   - echo sendmail_path=/usr/bin/env catchmail >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - mailcatcher
   - mkdir build
   - grunt start-hub &
   - grunt serve &
   - sleep 60

   script:
   - travis_retry vendor/bin/phpunit --configuration=phpunit.acceptance.xml

 - &mutation
   env:
   - REPORT=mutation-score

   install:
   - composer install
   - gem install mailcatcher

   before_script:
   - echo sendmail_path=/usr/bin/env catchmail >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - mailcatcher

   script:
   - vendor/bin/infection --threads=16 --only-covered

 - <<: *test-unit
   env:
   - REPORT=code-coverage

   script:
   - DB_URL=mysql://root:test@127.0.0.1/test vendor/bin/phpunit --coverage-clover=build/mysql.xml
   - DB_URL=postgres://postgres:test@127.0.0.1/test vendor/bin/phpunit --coverage-clover=build/pgsql.xml
   - DB_URL=sqlite://test.sqlite vendor/bin/phpunit --coverage-clover=build/sqlite.xml

   after_success:
   - vendor/bin/php-coveralls
   - wget https://scrutinizer-ci.com/ocular.phar
   - php ocular.phar code-coverage:upload --format=php-clover build/sqlite.xml

notifications:
 email:
 - team@redaxscript.com
