language: php

php: 7.1

before_install:
- composer global require hirak/prestissimo

jobs:
 include:
 - &lint
   env:
   - TYPE=lint

   install:
   - nvm install 9
   - npm install --global grunt-cli
   - npm install
   - composer self-update
   - composer install
   script:
   - grunt

 - &test
   env:
   - TYPE=test

   services:
   - mysql
   - postgresql

   install:
   - composer self-update
   - composer install
   - gem install mailcatcher

   before_script:
   - echo sendmail_path=/usr/bin/env catchmail --smtp-ip 127.0.0.1 --smtp-port 1025 -f test@test.com >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - mysql -u root -e 'create database test'
   - mysqladmin -u root password test
   - psql -U postgres -c 'create database test'
   - psql -U postgres -c 'alter user postgres with password '\'test\'

   script:
   - mailcatcher
   - DB_URL=mysql://root:test@127.0.0.1/test vendor/bin/phpunit
   - DB_URL=postgres://postgres:test@127.0.0.1/test vendor/bin/phpunit
   - DB_URL=sqlite://test.sqlite vendor/bin/phpunit

 - <<: *test
   php: 7.2

 - <<: *test
   php: nightly

 - <<: *test
   env:
   - TYPE=report

   script:
   - mailcatcher
   - DB_URL=mysql://root:test@127.0.0.1/test vendor/bin/phpunit --coverage-clover=build/mysql.xml
   - DB_URL=postgres://postgres:test@127.0.0.1/test vendor/bin/phpunit --coverage-clover=build/pgsql.xml
   - DB_URL=sqlite://test.sqlite vendor/bin/phpunit --coverage-clover=build/sqlite.xml

   after_success:
   - vendor/bin/coveralls
   - wget https://scrutinizer-ci.com/ocular.phar
   - php ocular.phar code-coverage:upload --format=php-clover build/sqlite.xml

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
