language: php

php: 7.2

before_install:
- composer global require hirak/prestissimo

jobs:
 include:
 - &lint
   env:
   - LINT

   install:
   - composer install
   - nvm install 10
   - npm install --global grunt-cli
   - npm install

   script:
   - grunt

 - &build
   addons:
    apt:
     packages:
     - fontforge

   env:
   - BUILD

   install:
   - nvm install 10
   - npm install --global grunt-cli
   - npm install

   script:
   - grunt build

 - &test-unit
   env:
   - TEST=unit

   services:
   - mysql
   - postgresql

   install:
   - composer install
   - gem install mailcatcher

   before_script:
   - echo sendmail_path=/usr/bin/env catchmail >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - mailcatcher
   - mysql -u root -e 'create database test'
   - mysqladmin -u root password test
   - psql -U postgres -c 'create database test'
   - psql -U postgres -c 'alter user postgres with password '\'test\'

   script:
   - DB_URL=mysql://root:test@127.0.0.1/test vendor/bin/phpunit
   - DB_URL=postgres://postgres:test@127.0.0.1/test vendor/bin/phpunit
   - DB_URL=sqlite://test.sqlite vendor/bin/phpunit

 - <<: *test-unit
   php: 7.3
 
 - &test-acceptance
   addons:
    apt:
     packages:
     - fontforge
     - google-chrome-stable

   env:
   - TEST=acceptance

   install:
   - composer install
   - nvm install 10
   - npm install --global grunt-cli
   - npm install

   before_script:
   - mkdir build
   - grunt start-hub &
   - grunt serve &
   - sleep 60

   script:
   - vendor/bin/phpunit --configuration=phpunit.acceptance.xml

 - &mutation
   env:
   - REPORT=mutation-score

   install:
   - composer install
   - gem install mailcatcher

   before_script:
   - echo sendmail_path=/usr/bin/env catchmail >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - mailcatcher

   script:
   - vendor/bin/infection --threads=10 --only-covered

 - <<: *test-unit
   env:
   - REPORT=code-coverage

   script:
   - DB_URL=mysql://root:test@127.0.0.1/test vendor/bin/phpunit --coverage-clover=build/mysql.xml
   - DB_URL=postgres://postgres:test@127.0.0.1/test vendor/bin/phpunit --coverage-clover=build/pgsql.xml
   - DB_URL=sqlite://test.sqlite vendor/bin/phpunit --coverage-clover=build/sqlite.xml

   after_success:
   - vendor/bin/php-coveralls
   - wget https://scrutinizer-ci.com/ocular.phar
   - php ocular.phar code-coverage:upload --format=php-clover build/sqlite.xml

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
