language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0

install:
- composer self-update
- composer install --ignore-platform-reqs
- npm install
- npm install -g grunt-cli

script:
- npm test

after_script:
- php vendor/bin/coveralls --verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover.xml

deploy:
 provider: heroku
 strategy: api
 app: redaxscript
 api_key:
  secure: CvUp6rO6I7+HZCj/kRGPnm/5P/Inwf4MXiaCdOnCoQ+2MTj8yZf6inzM9tybFmJHuaom2bB/lyxZw77DUalqRbF9wmj5haxa98Zp9SwwxvgY6NMOI2be3pMcFpgI9po9pO9Hc2Wltt6y144su1hBbKHavQXhy3IUV4o0DLfFW/k=

notifications:
 irc:
  - chat.freenode.net#redaxscript
 webhooks:
  - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
